name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: thumbv6m-none-eabi
        override: true

    - name: Install dependencies
      run: cargo instal flip-link

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
