name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        toolchain: nightly
    - name: Build
      run: rustup update nightly; rustup default nightly; rustup target add thumbv6m-none-eabi; cargo build --verbose
    - name: Run tests
      run: rustup update nightly; rustup default nightly; rustup target add thumbv6m-none-eabi; cargo test --verbose
